const USER_JOINED = 'USER_JOINED';
const MESSAGE_SEND = 'MESSAGE_SEND';
const UPDATE_USER_SOCKET = 'UPDATE_USER_SOCKET';
const GET_HIGH_SCORES = 'GET_HIGH_SCORES';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGIN_MESSAGE = 'USER_LOGIN_MESSAGE';

module.exports = {
  USER_JOINED, MESSAGE_SEND, UPDATE_USER_SOCKET, GET_HIGH_SCORES,USER_LOGIN_MESSAGE,USER_LOGIN
};
